#!/usr/bin/env bash
#Displays PID along with the process name or processes that contain the word bash
pids=$(pgrep -f bash)

for pid in $pids; do
	process_name=$(ps -p "$pid" -o comm=)
	echo "PID: $pid, process Name: $process_name"
done
