#!/usr/bin/env bash
#Displays 1 - 20 with some strings in between using echo with a case statement

counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo $counter
            echo "bad luck from China"
            ;;
        9)
            echo $counter
            echo "bad luck from Japan"
            ;;
        17)
            echo $counter
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done

