#!/usr/bin/env bash
#Displays file in the current directory

for file in *; do
    # Check if the file is a regular file and not hidden
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
        # Extract the part of the name after the first dash
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_after_dash"
    fi
done

