#!/usr/bin/env bash
# Check if the script is running on Docker
if [ -f /.dockerenv ]; then
    # Update localhost to 127.0.0.2
    sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

    # Update facebook.com to 8.8.8.8
    sudo sed -i 's/\(.*\)facebook.com/\1 8.8.8.8 facebook.com/' /etc/hosts

    echo "Hosts file updated successfully."
else
    echo "Please run this script inside a Docker container."
fi

